apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: {app: ingestion-service}
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-service
        image: 
        command: celery -A src.celery_app worker --queues ingestion --concurrency 2
        envFrom:
        - configMapRef:
            name: rag-common-config
        - secretRef:
            name: rag-common-secret