apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- ./secrets

images:
- name: ghcr.io/silverd087/raglab-backend
  newName: ghcr.io/silverd087/raglab-backend
  newTag: sha-2ee9544
- name: ghcr.io/silverd087/raglab-frontend
  newName: ghcr.io/silverd087/raglab-frontend
  newTag: sha-45aff01

namespace: development

patches:
- path: patches/rag-service-replicas.yaml
  target:
    kind: Deployment
    name: rag-service-deployment
