apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml

images:
- name: frontend
  newName: raglab/frontend
  newTag: prod

- name: rag-service
  newName: raglab/rag-service
  newTag: prod

- name: evaluation-service
  newName: raglab/evaluation-service
  newTag: prod

- name: ingestion-service
  newName: raglab/ingestion-service
  newTag: prod

secretGenerator:
  - name: rag-infra-secret
    envs: [infra-secret.env]
  - name: rag-app-secret
    envs: [app-secret.env]


namespace: production