apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: {app: rag-service}
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
      - name: rag-service
        image: ghcr.io/silverd087/raglab-backend
        command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
          - containerPort: 8000
        envFrom:
        - configMapRef:
            name: rag-common-config
        - secretRef:
            name: rag-infra-secret
        - secretRef:
            name: rag-app-secret
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 12
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 24
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 8
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1500m
            memory: 1536Mi