---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: celery-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    RABBITMQ_URL: AgAILpREZw4DmCByzhdXX+uV1bmgOJPO0CvUrXixvpf4aLumhda/rSMR6YaM1WyOoh5A0lAg60FcJziQac3VB9LuifjTpVwxCSBk/NnBs4rB5w6B+Xif3G70+S9+KxmsDaCNJd2egwuOJNt25TJUb3XkxfXCe/6MTUY4AIupcmgA2A+z0/ZF58vcNIAKaMJGt2/SOxyjR2f2+LLUWLhvXShiVgTkLTGf213XNwWNmiPTqPf+Guk/H2Kbk3uHw3P/nvW+xSm1wcB7LU5WlELGxgWTAfmyg8bzZWOxqgNbsipxafQsslhyJCBCzmQL2ADJ22719FlW/bT5wcZuzQPmBQ/IYU56JQ4HOpc0NHaRu4y5Z8bl9l3JockyISjEdSXEZhXgqUuQhawGv2GUZOE+4K9Sf6BtOd6SVxBoq5CCAMKD3c/1ACUiyu4WMjSpysnjs+z2cfACS7tPJewwf2DykUjDNhV7rwlS5trrYL18gZUt3x7/2poEr8NSao4r0nNC/MN5csfZ7rfjGlvewGgAVx5pkmtQWoJXbhbh7DOnEtsu2yptdpH8fsiOhBQSsWGF24oUGIcJ93jECWcXH+a/lJMaeghSHmRfb1/oDeM3Gou/q0fuwjf0pPSmrYSOip5v+sOC5FqniXFUysPUeUm9f6C/iOScrMNQWGdMTFdVtyCfcugy9WIGoe0PWLwAs4F4mjN9oOhYSkpx06xiwxejDSj63WKkaoBok2McPUikhWFsZFtx6IOEgXscGOGeDm1x1cNB0mgM51eWQmBJkZ0FUxl4vaun
  template:
    metadata:
      creationTimestamp: null
      name: celery-exporter-config
      namespace: monitoring
