---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: celery-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    RABBITMQ_URL: AgBLk4jO5fLxZiwYGXycqe2Jj3Oi/PLr8nweGl93xRbms3h7hdEPuWfOLn31J9+tTznAzwn0iBUUEBK1teIiQbQJkqR2+kb61JlV5Z+Ci49LU3vSxhlJ5H5OfXo+6RxW0Qqitu9BKce+ObvkC6g/Fq44+yx1tZLTr7zNeMoO19AyU8qT3/zBbcledtOVWXTZffj2oWSg85mo1WZ7W8HCXwZyTnjDh57n/GNk/kaG2IyDTa+fXxhUsGyasKwDU+1vWNeQDVieaXIagWYPe2Yr/scl/R9RQe4qiUury9xsAUItewb/p/CIPLj6yHN1dpzmLQygpEE7bvK9/4Ihbjexa7hBRSl4O8Yds5hCvL8/dFWPZd/tX6o/FIbEneXDKDCLQMXWiNXYcRP0YpiOSlavqfGAS5ghHd40yJB8vgw2C3wptfg9fCYJXrtgoc5KB8KcBMlBx/NJXrOHxSZsnM9AAyuyg2RM/PsyZjtWKTwJrodyT/N308TTbOt/xxrO3GzUSyDXaiu1WPd/PPtzgzkccEicnoOb5jBQAV+0s2VJUMahiYPjfIl8aX3GsLudiwPKeAVsM9lZ2iPMwhD/LKZcdvoujjWN3+edC2522gPk0qskMILkajPuEv+faewjQn+hHjPfusmMweLsgR85FBxfgrAOFg6LRvd9nPqUlZhkLA4WZrzqs8BdkI31n+kMrH0HQE4hF1U9Fk/p6y6fs7yFEh2P5oOwRMBElZC9Tuyj4AFqmWgVBW8bapve+ECuCS3h8zKQ9syFG5H+w2MOj3C642zAkeJw
  template:
    metadata:
      creationTimestamp: null
      name: celery-exporter-config
      namespace: monitoring
