apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: {app: evaluation-service}
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
      - name: evaluation-service
        image: 
        command: celery -A src.celery_app worker --queues evaluation --concurrency 1
        envFrom:
        - configMapRef:
            name: rag-common-config
        - secretRef:
            name: rag-common-secret