apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: {app: ingestion-service}
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-service
        image: ghcr.io/silverd087/raglab-backend
        command: ["celery", "-A", "src.celery_app", "worker", "-E", "--queues", "ingestion", "--concurrency", "2"]
        envFrom:
        - configMapRef:
            name: rag-common-config
        - secretRef:
            name: rag-infra-secret
        - secretRef:
            name: rag-app-secret
        startupProbe:
          exec:
            command:
            - bash
            - -c
            - grep -q "celery" /proc/1/cmdline   
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - grep -q "celery" /proc/1/cmdline
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 2Gi