apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raglab-dev
  namespace: argocd
spec:
  project: default 
  source: 
    repoURL: "https://github.com/Silverd087/RAG-Lab-Infra.git"
    targetRevision: main
    path: overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development
  syncPolicy:
    syncOptions:
      - CreateNamespace=true