apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels: {app: postgres}
  updateStrategy:
    type: RollingUpdate     
  template:
    metadata:
      labels: {app: postgres}
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports: [{containerPort: 5432}]
        volumes:
        - name: data
          persistentVolumeClaim: postgres-pvc
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data